operato.logis.samsung.name: samsung
operato.logis.samsung.version: 1.0.0.0
operato.logis.samsung.built.at: 2025-01-15 16:00:00
operato.logis.samsung.projectName: logis-samsung
operato.logis.samsung.description: Operator Logis Samsung MW Project
operato.logis.samsung.parentModule: logis
operato.logis.samsung.basePackage: operato.logis.samsung
operato.logis.samsung.scanEntityPackage: operato.logis.samsung.entity
operato.logis.samsung.scanServicePackage: operato.logis.samsung.rest