operato.logis.wcs.name: wcs
operato.logis.wcs.version: 1.0.0.0
operato.logis.wcs.built.at: 2022-02-26 16:00:00
operato.logis.wcs.projectName: logis-wcs
operato.logis.wcs.description: Operator Logis WCS Project
operato.logis.wcs.parentModule: logis
operato.logis.wcs.basePackage: operato.logis.wcs
operato.logis.wcs.scanEntityPackage: operato.logis.wcs.entity
operato.logis.wcs.scanServicePackage: operato.logis.wcs.rest