operato.logis.connector.name: connector
operato.logis.connector.version: 1.0.0.0
operato.logis.connector.built.at: 2022-02-26 16:00:00
operato.logis.connector.projectName: logis-connector
operato.logis.connector.description: Operator Logis Connector Project
operato.logis.connector.parentModule: logis
operato.logis.connector.basePackage: operato.logis.connector
operato.logis.connector.scanEntityPackage: operato.logis.connector.entity
operato.logis.connector.scanServicePackage: operato.logis.connector.rest

## AES 256 key
operato.logis.connector.sap.rfc.aeskey:ThisIsMy32ByteSecretKey123456789
## SAP Connect Data
operato.logis.connector.sap.rfc.abapas:ABAP_AS_WITHOUT_POOL
operato.logis.connector.sap.rfc.ashost:vhcwlcoqcs.sap.coway.do
operato.logis.connector.sap.rfc.sysnr:00
operato.logis.connector.sap.rfc.lang:KO
operato.logis.connector.sap.rfc.client:100
operato.logis.connector.sap.rfc.client.other:500
operato.logis.connector.sap.rfc.group:TITAN
operato.logis.connector.sap.rfc.r3name:COQ
operato.logis.connector.sap.rfc.user:CORFCWES01
operato.logis.connector.sap.rfc.passwd:Coway123!
## SAP jco Pool Config
# Minimum number of idle connections kept in the pool at all times, even if unused.
operato.logis.connector.sap.rfc.pool-capacity=10
# Maximum number of connections allowed simultaneously; blocks if exceeded
operato.logis.connector.sap.rfc.peak-limit=20
# Time (in milliseconds) after which idle connections are automatically removed from the pool.(10 minutes)
operato.logis.connector.sap.rfc.expiration-time=600000
# Maximum time (in milliseconds) to wait for a connection from the pool before timing out.(30 seconds)
operato.logis.connector.sap.rfc.max-get-time=30000

# SAP Module enable true
connector.sap.enabled=false

vision.client.ip=localhost
vision.client.port=8080

hokusho.ecs.base-url: http://192.168.100.104:8011/rest/hokusho