operato.logis.lms.name: lms
operato.logis.lms.version: 1.0.0.0
operato.logis.lms.built.at: 2026-01-09 13:00:00
operato.logis.lms.projectName: logis-lms
operato.logis.lms.description: Logistics Monitoring System Project
operato.logis.lms.parentModule: logis
operato.logis.lms.basePackage: operato.logis.lms
operato.logis.lms.scanEntityPackage: operato.logis.lms.entity
operato.logis.lms.scanServicePackage: operato.logis.lms.rest
kakao.client-id=e31ef40436526f5dc2d2cce18df0e5ca
