operato.logis.asrs.name: asrs
operato.logis.asrs.version: 1.0.0.0
operato.logis.asrs.built.at: 2022-02-26 16:00:00
operato.logis.asrs.projectName: logis-asrs
operato.logis.asrs.description: Operator Logis ASRS Project
operato.logis.asrs.parentModule: logis
operato.logis.asrs.basePackage: operato.logis.asrs
operato.logis.asrs.scanEntityPackage: operato.logis.asrs.entity
operato.logis.asrs.scanServicePackage: operato.logis.asrs.rest