INSERT INTO MENUS (
    ID, NAME, DESCRIPTION, PARENT_ID, TEMPLATE, MENU_TYPE, CATEGORY, RANK, ICON_PATH, HIDDEN_FLAG,
    ROUTING, ROUTING_TYPE, DETAIL_FORM_ID, DETAIL_LAYOUT, RESOURCE_TYPE, RESOURCE_NAME, RESOURCE_URL,
    GRID_SAVE_URL, ID_FIELD, TITLE_FIELD, DESC_FIELD, PAGINATION, ITEMS_PROP, TOTAL_PROP, FIXED_COLUMNS,
    DOMAIN_ID, CREATOR_ID, UPDATER_ID, CREATED_AT, UPDATED_AT, PAGINATION_VALUE, PROVISION_TYPE
)
SELECT
    uuid_generate_v4() AS ID, NAME, DESCRIPTION, PARENT_ID, TEMPLATE, MENU_TYPE, CATEGORY, RANK,
    ICON_PATH, HIDDEN_FLAG, ROUTING, ROUTING_TYPE, DETAIL_FORM_ID, DETAIL_LAYOUT, RESOURCE_TYPE,
    RESOURCE_NAME, RESOURCE_URL, GRID_SAVE_URL, ID_FIELD, TITLE_FIELD, DESC_FIELD, PAGINATION,
    ITEMS_PROP, TOTAL_PROP, FIXED_COLUMNS, :targetDomainId AS DOMAIN_ID, CREATOR_ID, UPDATER_ID, CREATED_AT, UPDATED_AT,
    PAGINATION_VALUE, PROVISION_TYPE
FROM
    menus
WHERE
    PROVISION_TYPE IN (:service) AND DOMAIN_ID = :sourceDomainId