INSERT INTO MENU_DETAIL_COLUMNS (
    ID, MENU_DETAIL_ID, NAME, DESCRIPTION, RANK, TERM,
    COL_TYPE, COL_SIZE, NULLABLE, REF_TYPE, REF_NAME, REF_URL, REF_PARAMS, REF_RELATED,
    SEARCH_RANK, SORT_RANK, REVERSE_SORT, VIRTUAL_FIELD, SEARCH_NAME, SEARCH_EDITOR,
    SEARCH_OPER, SEARCH_INIT_VAL, GRID_RANK, GRID_EDITOR, GRID_FORMAT, GRID_VALIDATOR,
    GRID_WIDTH, GRID_ALIGN, UNIQ_RANK, FORM_EDITOR, FORM_VALIDATOR, FORM_FORMAT,
    DEF_VAL, RANGE_VAL, IGNORE_ON_SAVE, EXT_FIELD, DOMAIN_ID
)
SELECT
    uuid_generate_v4() AS ID, B.ID AS MENU_DETAIL_ID, C.NAME, C.DESCRIPTION,
    C.RANK, C.TERM, C.COL_TYPE, C.COL_SIZE, C.NULLABLE, C.REF_TYPE, C.REF_NAME,
    C.REF_URL, C.REF_PARAMS, C.REF_RELATED, C.SEARCH_RANK, C.SORT_RANK, C.REVERSE_SORT,
    C.VIRTUAL_FIELD, C.SEARCH_NAME, C.SEARCH_EDITOR, C.SEARCH_OPER, C.SEARCH_INIT_VAL,
    C.GRID_RANK, C.GRID_EDITOR, C.GRID_FORMAT, C.GRID_VALIDATOR, C.GRID_WIDTH,
    C.GRID_ALIGN, C.UNIQ_RANK, C.FORM_EDITOR, C.FORM_VALIDATOR, C.FORM_FORMAT,
    C.DEF_VAL, C.RANGE_VAL, C.IGNORE_ON_SAVE, C.EXT_FIELD, b.DOMAIN_ID AS DOMAIN_ID
FROM
    (SELECT * FROM MENU_DETAILS WHERE domain_id = :sourceDomainId) a,
    (SELECT * FROM MENU_DETAILS WHERE domain_id = :targetDomainId) b,
    (SELECT * FROM MENU_DETAIL_COLUMNS WHERE domain_id = :sourceDomainId) C
WHERE
    a.name = b.name AND a.id = c.MENU_DETAIL_ID