SELECT
    *
FROM
    WCS_STOCK_AUTO
WHERE CRANE_NO = :craneNo
  AND RACK_LOCKED = 0
  AND RACK_DISABLED = 0
  AND CRANE_DISABLED = 0
  AND (TASK_ID IS NULL OR TASK_ID = '')
  AND (STOCK_ID IS NULL OR STOCK_ID = '')
  AND (
    (CRANE_NO % 2 = 1 AND LOC_SIDE = 'RIGHT' AND LOC_ROW = 1) /* 홀수 크레인 (201, 203, 205) */
        OR (CRANE_NO % 2 = 0 AND LOC_SIDE = 'LEFT'  AND LOC_ROW = 1) /* 짝수 크레인 (202, 204, 206) */
  )
ORDER BY LOC_DEEP DESC
LIMIT 1
FOR UPDATE