########################################
#			Server Info 			   #
########################################
spring.application.name=Anyware ASRS Dev Server
server.port=9500

info.id=next-wcs-boot

########################################
#				Database 			   #
########################################
spring.datasource.name=Elidom
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://10.30.1.32:5432/logis-asrs?currentSchema=logis_asrs
spring.datasource.username=logis_asrs
spring.datasource.password=anyware123!
spring.datasource.dbcp.max-active=50

########################################
#				Redis                  #
########################################
spring.session.store-type=redis
spring.session.redis.flush-mode=immediate
server.servlet.session.timeout=3600000
spring.data.redis.host=localhost
spring.data.redis.password=
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-wait=5000
spring.data.redis.lettuce.pool.min-idle=5
spring.data.redis.timeout=5000

########################################
#				DBIST		  		   #
########################################
dml.domain=logis_asrs
dbist.ddl.enable=false
dbist.base.entity.path=xyz.elidom,xyz.anythings,operato.logis.asrs
dbist.entity.validateBeforeSave=true
dbist.ddl.tablespace.data=anythings
dbist.ddl.tablespace.idx=anythings

## Dbist AOP
sqlAspect.enabled=true
sqlAspect.prettyPrint=true
sqlAspect.combinedPrint=true
sqlAspect.includeElapsedTime=true

########################################
#         Task Scheduler               #
########################################
scheduler.pool.size=10
scheduler.shutdown.wait=true
scheduler.shutdown.await-seconds=60

########################################
#			Stomp Server		  	   #
########################################
stomp.server.host=localhost
stomp.server.port=9002
stomp.client.url=localhost

########################################
#				Logging 			   #
########################################
logging.config=classpath:WEB-INF/logback-spring-dev.xml

########################################
#				E-Mail  			   #
########################################
mail.smtp.host=smtp.nearsolution.co.kr
mail.smtp.port=587
mail.smtp.user=services@nearsolution.co.kr
mail.smtp.password=1q2w3e4r~!
mail.smtp.protocol=smtp
mail.smtp.auth=true
mail.smtp.starttls.enable=true

########################################
#		File Upload Max Size  		   #
########################################
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
upload.file.limit.size=500

########################################
#		JACKSON-Serialization  		   #
########################################
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.serialization.INDENT_OUTPUT=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.serialization-inclusion=non_null
spring.jackson.time-zone=Asia/Seoul

########################################
#			Transaction		  		   #
########################################
transactionManager.defaultTimeout=300


########################################
#			Security		  		   #
########################################
management.security.enabled=false
security.password.encoder.algorithm=SHA-256

# Field Encryption/Decryption
address.crypto.key.id=1
address.crypto.key.b64=${APP_ADDRESS_AES_KEY_B64:}
edge.server.crypto.key.id=1
edge.server.crypto.key.b64=${APP_EDGE_SERVER_AES_KEY_B64:}

############################################################
#			REDIS WAS URLS		   	   #
############################################################
redis.was.urls=localhost:9500

#############################################################
#			Middleware Info  		    #
#############################################################
mq.module.use=false
mq.broker.address=192.168.50.196
# def 5672
mq.broker.port=5672
# def 15672
mq.broker.api.port=15672

#def admin
mq.broker.user.id=admin
mq.broker.user.pw=admin
mq.broker.exchange.default=amq.direct

# system receive queue
mq.system.receive.queue.consume.count=5

# trace settings
# type : db, file, elastic
mq.trace.use=false
mq.trace.type=elastic
mq.trace.keep.date=5
mq.trace.delete.time=01
mq.trace.consume.count=5

mq.trace.elastic.address=192.168.50.196
mq.trace.elastic.port=9200

########################################
#			Initial Setup			   #
########################################
elidom.initial.setup=false
elidom.initial.domain.id=6
elidom.initial.domain.name=Core Dev Boot
elidom.initial.domain.brand_name=Core Dev Boot
elidom.initial.domain.url=services@nearsolution.co.kr
elidom.initial.admin.id=admin
elidom.initial.admin.name=admin
elidom.initial.admin.email=services@nearsolution.co.kr
elidom.initial.admin.passwd=admin
elidom.initial.storage.root=/storage
elidom.initial.seed.source=seed-file
elidom.initial.seed.base_url=http://admin.nearsolution.co.kr/rest
elidom.initial.seed.id=8a2438a7-35a0-48c5-8c59-d2501c1f5235

#####################################################################################
#				When Initial Setup - You must change this properties 			   	#
#####################################################################################
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true
spring.aop.proxy-target-class=true
server.tomcat.relaxed-query-chars=[,],{,}

logging.level.org.springframework.boot.autoconfigure.quartz=DEBUG
logging.level.org.quartz=DEBUG