operato.logis.inventory.name: kia
operato.logis.inventory.version: 1.0.0.0
operato.logis.inventory.built.at: 2022-02-26 16:00:00
operato.logis.inventory.projectName: logis-kia
operato.logis.inventory.description: Operator Logis KIA Project
operato.logis.inventory.parentModule: logis
operato.logis.inventory.basePackage: operato.logis.kia
operato.logis.inventory.scanEntityPackage: operato.logis.kia.entity
operato.logis.inventory.scanServicePackage: operato.logis.kia.rest