operato.logis.changwon.name: changwon
operato.logis.changwon.version: 1.0.0.0
operato.logis.changwon.built.at: 2022-02-26 16:00:00
operato.logis.changwon.projectName: logis-changwon
operato.logis.changwon.description: Operator Logis Changwon Project
operato.logis.changwon.parentModule: logis
operato.logis.changwon.basePackage: operato.logis.changwon
operato.logis.changwon.scanEntityPackage: operato.logis.changwon.entity
operato.logis.changwon.scanServicePackage: operato.logis.changwon.rest