operato.logis.simulator.name: simulator
operato.logis.simulator.version: 1.0.0.0
operato.logis.simulator.built.at: 2022-02-26 16:00:00
operato.logis.simulator.projectName: logis-simulator
operato.logis.simulator.description: Operator Logis Simulator Project
operato.logis.simulator.parentModule: logis
operato.logis.simulator.basePackage: operato.logis.simulator
operato.logis.simulator.scanEntityPackage: operato.logis.simulator.entity
operato.logis.simulator.scanServicePackage: operato.logis.simulator.rest