INSERT INTO PERMISSIONS (
    ID, ROLE_ID, RESOURCE_ID, RESOURCE_TYPE, ACTION_NAME, METHOD_NAME, DOMAIN_ID
)
SELECT
    LOWER(
	    REGEXP_REPLACE(
	        RAWTOHEX(SYS_GUID()),
	        '(.{8})(.{4})(.{4})(.{4})(.{12})',
	        '\1-\2-\3-\4-\5'
	    )
	) AS ID, D.ID AS ROLE_ID, E.ID AS RESOURCE_ID, A.RESOURCE_TYPE, A.ACTION_NAME, A.METHOD_NAME, D.DOMAIN_ID AS DOMAIN_ID
FROM
    PERMISSIONS A,
    ROLES B,
    MENUS C,
    (SELECT * FROM ROLES WHERE DOMAIN_ID = :targetDomainId) D,
    (SELECT * FROM MENUS WHERE DOMAIN_ID = :targetDomainId) E
WHERE
    A.DOMAIN_ID = :sourceDomainId
    AND A.ROLE_ID = B.ID
    AND A.RESOURCE_ID = C.ID
    AND B.NAME = D.NAME
    AND C.NAME = E.NAME