anyware.wcs.name: anyware
anyware.wcs.version: 1.0.0.0
anyware.wcs.built.at: 2022-04-18 16:00:00
anyware.wcs.projectName: anyware-wcs
anyware.wcs.description: Anyware WCS Boot Project
anyware.wcs.parentModule: logis
anyware.wcs.basePackage: xyz.anyware.wcs
anyware.wcs.scanEntityPackage: xyz.anyware.wcs.entity
anyware.wcs.scanServicePackage: xyz.anyware.wcs.rest