operato.logis.posco.name: posco
operato.logis.posco.version: 1.0.0.0
operato.logis.posco.built.at: 2022-02-26 16:00:00
operato.logis.posco.projectName: logis-posco
operato.logis.posco.description: Operator Logis Posco Project
operato.logis.posco.parentModule: logis
operato.logis.posco.basePackage: operato.logis.posco
operato.logis.posco.scanEntityPackage: operato.logis.posco.entity
operato.logis.posco.scanServicePackage: operato.logis.posco.rest