operato.logis.ecs.base.name:ecs-base
operato.logis.ecs.base.version:1.0.0.0
operato.logis.ecs.base.built.at:2022-02-26 16:00:00
operato.logis.ecs.base.projectName:logis-ecs-base
operato.logis.ecs.base.description:Operator Logis ECS Base Project
operato.logis.ecs.base.parentModule:logis
operato.logis.ecs.base.basePackage:operato.logis.ecs.base.ecs
operato.logis.ecs.base.scanEntityPackage:operato.logis.ecs.base.ecs.entity
operato.logis.ecs.base.scanServicePackage:operato.logis.ecs.base.ecs.rest