WITH VALID_STOCK AS (
    SELECT
        *
    FROM
        WCS_STOCK_INFO
    WHERE ITEM_CODE = :itemCode
      AND ITEM_OWNER = :itemOwner
      AND STOCK_LOCKED < 2  -- IDLE, SORT 상태
      AND STOCK_DISABLED = 0
)

SELECT
    A.*
FROM
    WCS_STOCK_AUTO A
JOIN
    VALID_STOCK S ON S.STOCK_ID = A.STOCK_ID
WHERE RACK_LOCKED < 2  -- IDLE, SORT 상태
  AND RACK_DISABLED = 0
  AND CRANE_DISABLED = 0
ORDER BY
    S.INB_DATE ASC,
    S.STOCK_LOCKED ASC,
    A.LOC_DEEP ASC
LIMIT 1
FOR UPDATE